name: Release a new version

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: github
      - name: View settings.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Set up Git
        run: |
          git config user.email "tech@onlydust.com"
          git config user.name "OnlyDust Tech team"
      - name: Prepare release
        run: ./mvnw --batch-mode release:prepare
      - name: Perform release
        run: ./mvnw release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}