name: Release a new version

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw --batch-mode release:prepare
      - run: ./mvnw release:perform
